# Generated by Django 3.2.5 on 2022-10-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=80)),
                ('food_description', models.TextField()),
                ('food_quantity', models.IntegerField()),
                ('food_selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('food_discound_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('food_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_food)),
                ('status', models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Preparing', 'Order Preparing'), ('Order On-Delivery', 'Order On-Delivery'), ('Order Delivered', 'Order Delivered')], max_length=25)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('food_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_category_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_city', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_state', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_location_latitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restaurant_location_longitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restaurant_is_open', models.BooleanField(default=False)),
                ('restaurant_hours_of_operation', models.TextField()),
                ('restaurant_opening_time', models.TimeField()),
                ('restaurant_closing_time', models.TimeField()),
                ('restaurant_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_restaurant)),
                ('restaurant_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('restaurant_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAttribute',
            fields=[
                ('Restaurant_attribute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.restaurant')),
                ('bike_parking', models.CharField(max_length=150)),
                ('accept_credit_cards', models.BooleanField(default=False)),
                ('garage_parking', models.BooleanField(default=False)),
                ('street_parking', models.BooleanField(default=False)),
                ('dog_allowed', models.BooleanField(default=False)),
                ('price_range', models.CharField(choices=[('Low Price', 'Low Price'), ('Medium Price', 'Medium Price'), ('Expensive', 'Expensive')], max_length=25)),
                ('valet', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blog_slug', models.SlugField(unique=True)),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_description', models.TextField()),
                ('blog_publish_date', models.DateField(auto_now_add=True)),
                ('blog_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_blog)),
                ('blog_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory')),
            ],
        ),
    ]
