# Generated by Django 3.2.5 on 2022-11-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blog_slug', models.SlugField(unique=True)),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_description', models.TextField()),
                ('blog_publish_date', models.DateField(auto_now_add=True)),
                ('blog_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_blog)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('food_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_category_title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_city', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_state', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_location_latitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restaurant_location_longitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restaurant_is_open', models.BooleanField(default=False)),
                ('restaurant_hours_of_operation', models.TextField()),
                ('restaurant_opening_time', models.TimeField()),
                ('restaurant_closing_time', models.TimeField()),
                ('restaurant_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_restaurant)),
                ('restaurant_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('restaurant_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAttribute',
            fields=[
                ('Restaurant_attribute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.restaurant')),
                ('bike_parking', models.CharField(max_length=150)),
                ('accept_credit_cards', models.BooleanField(default=False)),
                ('garage_parking', models.BooleanField(default=False)),
                ('street_parking', models.BooleanField(default=False)),
                ('dog_allowed', models.BooleanField(default=False)),
                ('price_range', models.CharField(choices=[('Low Price', 'Low Price'), ('Medium Price', 'Medium Price'), ('Expensive', 'Expensive')], max_length=25)),
                ('valet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal')], max_length=200)),
                ('town_city', models.CharField(choices=[('Pyuthan', 'Pyuthan'), ('kathmandu', 'kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Dhading', 'Dhading'), ('Kaski', 'Kaski'), ('Butwal', 'Butwal')], max_length=200)),
                ('shipping_address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the Way', 'On the Way'), ('Order Completed', 'Order Completed'), ('Order Cancelled', 'Order Cancelled'), ('Order Delivered', 'Order Delivered')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=80)),
                ('food_description', models.TextField()),
                ('food_quantity', models.IntegerField()),
                ('food_selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('food_discound_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('food_image', models.ImageField(upload_to=restaurant.models.get_file_path_for_food)),
                ('status', models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received'), ('Order Preparing', 'Order Preparing'), ('Order On-Delivery', 'Order On-Delivery'), ('Order Delivered', 'Order Delivered')], max_length=25)),
                ('is_featured', models.BooleanField(default=False)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.cart')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.customer'),
        ),
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('temporary_address', models.CharField(max_length=200)),
                ('working_address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer')),
            ],
        ),
    ]
