# Generated by Django 3.2.5 on 2022-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='msg_date',
            field=models.DateField(auto_now_add=True, default='2022-02-12'),
            preserve_default=False,
        ),
    ]
