# Generated by Django 3.2.5 on 2022-10-18 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_open', models.BooleanField(default=False)),
                ('hours_of_operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('restaurant_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImages',
            fields=[
                ('Restaurant_image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAttribute',
            fields=[
                ('Restaurant_attribute_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.restaurant')),
                ('bike_parking', models.CharField(max_length=150)),
                ('accept_credit_cards', models.BooleanField(default=False)),
                ('garage_parking', models.BooleanField(default=False)),
                ('street_parking', models.BooleanField(default=False)),
                ('dog_allowed', models.BooleanField(default=False)),
                ('price_range', models.CharField(choices=[('Low Price', 'Low Price'), ('Medium Price', 'Medium Price'), ('Expensive', 'Expensive')], max_length=25)),
                ('valet', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Restaurant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantimages'),
        ),
    ]
