# Generated by Django 4.1 on 2022-11-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_by", models.CharField(max_length=200)),
                ("shipping_address", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subtotal", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Order Received", "Order Received"),
                            ("Order Processing", "Order Processing"),
                            ("On the Way", "On the Way"),
                            ("Order Completed", "Order Completed"),
                            ("Order Cancelled", "Order Cancelled"),
                            ("Order Delivered", "Order Delivered"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.cart",
                    ),
                ),
            ],
        ),
    ]
