# Generated by Django 3.2.5 on 2022-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20221018_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimages',
            name='image',
            field=models.FileField(upload_to='restaurantsgwtc_rms_system'),
        ),
    ]
