# Generated by Django 3.2.5 on 2022-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Nepal', 'Nepal')], default='gg', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='gg', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='town_city',
            field=models.CharField(choices=[('Pyuthan', 'Pyuthan'), ('kathmandu', 'kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Dhading', 'Dhading'), ('Kaski', 'Kaski'), ('Butwal', 'Butwal')], default='gg', max_length=200),
            preserve_default=False,
        ),
    ]
